#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    FILE *f = fopen("kernel/gui/desktop.c", "r");
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *content = malloc(size + 1);
    fread(content, 1, size, f);
    content[size] = 0;
    fclose(f);

    // Localizar desktop_create_explorer
    char *start = strstr(content, "void desktop_create_explorer(void) {");
    char *end = strstr(start, "void desktop_create_sysinfo(void) {");
    
    char new_code[] = 
"#include \"icons/icon_folder.h\"\n"
"#include \"icons/icon_doc.h\"\n"
"#include \"icons/icon_image.h\"\n"
"#include \"icons/icon_video.h\"\n"
"#include \"icons/icon_add.h\"\n"
"#include \"icons/icon_search.h\"\n"
"\n"
"static void draw_icon_to_buffer(uint32_t *buffer, uint32_t buf_w, uint32_t buf_h, int32_t x, int32_t y, const uint32_t *icon_data, uint32_t icon_w, uint32_t icon_h) {\n"
"    if (!buffer) return;\n"
"    int32_t scaled_w = icon_w * g_ui_scale;\n"
"    int32_t scaled_h = icon_h * g_ui_scale;\n"
"    \n"
"    for (int32_t iy = 0; iy < scaled_h; iy++) {\n"
"        for (int32_t ix = 0; ix < scaled_w; ix++) {\n"
"            if (x + ix < 0 || x + ix >= (int32_t)buf_w || y + iy < 0 || y + iy >= (int32_t)buf_h) continue;\n"
"            \n"
"            uint32_t src_x = (ix << 8) / g_ui_scale;\n"
"            uint32_t src_y = (iy << 8) / g_ui_scale;\n"
"            \n"
"            uint32_t x0 = src_x >> 8;\n"
"            uint32_t y0 = src_y >> 8;\n"
"            uint32_t x1 = x0 + 1;\n"
"            uint32_t y1 = y0 + 1;\n"
"            if (x1 >= icon_w) x1 = icon_w - 1;\n"
"            if (y1 >= icon_h) y1 = icon_h - 1;\n"
"            \n"
"            uint32_t fx = src_x & 0xFF;\n"
"            uint32_t fy = src_y & 0xFF;\n"
"            \n"
"            uint32_t c00 = icon_data[y0 * icon_w + x0];\n"
"            uint32_t c01 = icon_data[y0 * icon_w + x1];\n"
"            uint32_t c10 = icon_data[y1 * icon_w + x0];\n"
"            uint32_t c11 = icon_data[y1 * icon_w + x1];\n"
"            \n"
"            uint32_t a00 = (c00 >> 24) & 0xFF, a01 = (c01 >> 24) & 0xFF;\n"
"            uint32_t a10 = (c10 >> 24) & 0xFF, a11 = (c11 >> 24) & 0xFF;\n"
"            uint32_t top_a = (a00 * (256 - fx) + a01 * fx) >> 8;\n"
"            uint32_t bot_a = (a10 * (256 - fx) + a11 * fx) >> 8;\n"
"            uint32_t alpha = (top_a * (256 - fy) + bot_a * fy) >> 8;\n"
"            \n"
"            if (alpha > 0) {\n"
"                uint32_t r00 = (c00 >> 16) & 0xFF, r01 = (c01 >> 16) & 0xFF;\n"
"                uint32_t r10 = (c10 >> 16) & 0xFF, r11 = (c11 >> 16) & 0xFF;\n"
"                uint32_t top_r = (r00 * (256 - fx) + r01 * fx) >> 8;\n"
"                uint32_t bot_r = (r10 * (256 - fx) + r11 * fx) >> 8;\n"
"                uint32_t fr = (top_r * (256 - fy) + bot_r * fy) >> 8;\n"
"                \n"
"                uint32_t g00 = (c00 >> 8) & 0xFF, g01 = (c01 >> 8) & 0xFF;\n"
"                uint32_t g10 = (c10 >> 8) & 0xFF, g11 = (c11 >> 8) & 0xFF;\n"
"                uint32_t top_g = (g00 * (256 - fx) + g01 * fx) >> 8;\n"
"                uint32_t bot_g = (g10 * (256 - fx) + g11 * fx) >> 8;\n"
"                uint32_t fg = (top_g * (256 - fy) + bot_g * fy) >> 8;\n"
"                \n"
"                uint32_t b00 = c00 & 0xFF, b01 = c01 & 0xFF;\n"
"                uint32_t b10 = c10 & 0xFF, b11 = c11 & 0xFF;\n"
"                uint32_t top_b = (b00 * (256 - fx) + b01 * fx) >> 8;\n"
"                uint32_t bot_b = (b10 * (256 - fx) + b11 * fx) >> 8;\n"
"                uint32_t fb = (top_b * (256 - fy) + bot_b * fy) >> 8;\n"
"                \n"
"                if (alpha == 255) {\n"
"                    buffer[(y + iy) * buf_w + (x + ix)] = (fr << 16) | (fg << 8) | fb;\n"
"                } else {\n"
"                    uint32_t bg = buffer[(y + iy) * buf_w + (x + ix)];\n"
"                    uint32_t bgr = (bg >> 16) & 0xFF;\n"
"                    uint32_t bgg = (bg >> 8) & 0xFF;\n"
"                    uint32_t bgb = bg & 0xFF;\n"
"                    \n"
"                    uint32_t r = (fr * alpha + bgr * (255 - alpha)) / 255;\n"
"                    uint32_t g = (fg * alpha + bgg * (255 - alpha)) / 255;\n"
"                    uint32_t b = (fb * alpha + bgb * (255 - alpha)) / 255;\n"
"                    \n"
"                    buffer[(y + iy) * buf_w + (x + ix)] = (r << 16) | (g << 8) | b;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"static void draw_rounded_rect_buffer(uint32_t *buffer, uint32_t buf_w, uint32_t buf_h, int32_t x, int32_t y, int32_t w, int32_t h, int32_t r, uint32_t color) {\n"
"    for (int32_t cy = y; cy < y + h; cy++) {\n"
"        for (int32_t cx = x; cx < x + w; cx++) {\n"
"            if (cx < 0 || cx >= (int32_t)buf_w || cy < 0 || cy >= (int32_t)buf_h) continue;\n"
"            \n"
"            int32_t dx = 0, dy = 0;\n"
"            if (cx < x + r) dx = (x + r - 1) - cx;\n"
"            else if (cx >= x + w - r) dx = cx - (x + w - r);\n"
"            if (cy < y + r) dy = (y + r - 1) - cy;\n"
"            else if (cy >= y + h - r) dy = cy - (y + h - r);\n"
"            \n"
"            if (dx*dx + dy*dy >= r*r) continue;\n"
"            buffer[cy * buf_w + cx] = color;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"void desktop_create_explorer(void) {\n"
"    uint32_t w = 680 * g_ui_scale;\n"
"    uint32_t h = 500 * g_ui_scale;\n"
"    window_t *win = wm_create_window(250 * g_ui_scale, 150 * g_ui_scale, w, h, \"Files / root / documents\");\n"
"    if (win && win->buffer) {\n"
"        /* Dark mode background */\n"
"        for (uint32_t i = 0; i < w * h; i++) {\n"
"            win->buffer[i] = 0x001C1E23;\n"
"        }\n"
"        \n"
"        /* Header (Seamless) */\n"
"        /* The title is drawn by compositor. We just draw the search icon. */\n"
"        draw_icon_to_buffer(win->buffer, w, h, w - (48 * g_ui_scale), 12 * g_ui_scale, icon_search, ICON_SEARCH_WIDTH, ICON_SEARCH_HEIGHT);\n"
"        \n"
"        /* Grid properties */\n"
"        int32_t start_x = 40 * g_ui_scale;\n"
"        int32_t start_y = 80 * g_ui_scale;\n"
"        int32_t item_w = 120 * g_ui_scale;\n"
"        int32_t item_h = 140 * g_ui_scale;\n"
"        int32_t box_size = 80 * g_ui_scale;\n"
"        \n"
"        /* Items (Projects, Graphics, Invoices, Backup, Renders, New) */\n"
"        struct { const char* name; const uint32_t* icon; uint32_t icon_w; uint32_t icon_h; uint32_t color; } items[] = {\n"
"            {\"Projects\", icon_folder, ICON_FOLDER_WIDTH, ICON_FOLDER_HEIGHT, 0xFF3B4455},\n"
"            {\"Graphics\", icon_image, ICON_IMAGE_WIDTH, ICON_IMAGE_HEIGHT, 0xFF2A3F3F},\n"
"            {\"Invoices.pdf\", icon_doc, ICON_DOC_WIDTH, ICON_DOC_HEIGHT, 0xFF3F2A3F},\n"
"            {\"Backup\", icon_folder, ICON_FOLDER_WIDTH, ICON_FOLDER_HEIGHT, 0xFF3B4455},\n"
"            {\"Renders\", icon_video, ICON_VIDEO_WIDTH, ICON_VIDEO_HEIGHT, 0xFF2A3F3F},\n"
"            {\"New\", icon_add, ICON_ADD_WIDTH, ICON_ADD_HEIGHT, 0xFF2A3F30}\n"
"        };\n"
"        \n"
"        for (int i = 0; i < 6; i++) {\n"
"            int col = i % 4;\n"
"            int row = i / 4;\n"
"            int32_t cx = start_x + col * item_w;\n"
"            int32_t cy = start_y + row * item_h;\n"
"            \n"
"            /* Draw rounded box */\n"
"            draw_rounded_rect_buffer(win->buffer, w, h, cx, cy, box_size, box_size, 16 * g_ui_scale, items[i].color & 0xFFFFFF);\n"
"            \n"
"            /* Draw icon */\n"
"            draw_icon_to_buffer(win->buffer, w, h, cx + (box_size - items[i].icon_w*g_ui_scale)/2, cy + (box_size - items[i].icon_h*g_ui_scale)/2, items[i].icon, items[i].icon_w, items[i].icon_h);\n"
"            \n"
"            /* Draw text */\n"
"            font_draw_string_to_buffer_scaled(win->buffer, w, h, cx + (box_size - strlen(items[i].name)*8*g_ui_scale)/2, cy + box_size + 12*g_ui_scale, items[i].name, 0x00A0A0A0, 0x001C1E23, g_ui_scale);\n"
"        }\n"
"    }\n"
"}\n\n";

    int start_idx = start - content;
    int end_idx = end - content;

    FILE *out = fopen("kernel/gui/desktop.c", "w");
    fwrite(content, 1, start_idx, out);
    fwrite(new_code, 1, strlen(new_code), out);
    fwrite(content + end_idx, 1, size - end_idx, out);
    fclose(out);
    free(content);
    return 0;
}