title   Genesi OS (Virtual Machine - VirtualBox / VMware)
sort-key C
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos-lts
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos-lts.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=n module_blacklist=pcspkr,vmwgfx nomodeset nvme_load=yes
