from PIL import Image
import sys

def convert_png_to_c_header(image_path, output_path, array_name):
    try:
        # Abre a imagem e converte para RGBA (suporte a transparência)
        img = Image.open(image_path).convert("RGBA")
        width, height = img.size
        
        out = f"/* Generated by img2c.py from {image_path} */\n"
        out += f"#ifndef {array_name.upper()}_H\n"
        out += f"#define {array_name.upper()}_H\n\n"
        out += f"#include <stdint.h>\n\n"
        out += f"#define {array_name.upper()}_WIDTH {width}\n"
        out += f"#define {array_name.upper()}_HEIGHT {height}\n\n"
        out += f"static const uint32_t {array_name}[{width * height}] = {{\n"
        
        pixels = list(img.getdata())
        for y in range(height):
            out += "    "
            for x in range(width):
                r, g, b, a = pixels[y * width + x]
                # Converte para formato ARGB 32-bits
                hex_color = f"0x{a:02X}{r:02X}{g:02X}{b:02X}"
                out += f"{hex_color}, "
            out += "\n"
            
        out += "};\n\n#endif\n"
        
        with open(output_path, "w") as f:
            f.write(out)
            
        print(f"Sucesso! Imagem convertida para: {output_path}")
        print(f"Para usar no C, faça: #include \"{output_path}\" e leia o array {array_name}.")
        
    except Exception as e:
        print(f"Erro ao processar imagem: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Uso: python3 img2c.py <input.png> <output.h> <array_name>")
        sys.exit(1)
        
    convert_png_to_c_header(sys.argv[1], sys.argv[2], sys.argv[3])
