#
# /etc/pacman-target.conf - Genesi OS
# Pacman configuration for target system installation
#

[options]
HoldPkg     = pacman glibc
Architecture = auto

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[genesi]
SigLevel = Optional TrustAll
Server = https://github.com/zFreshy/GenesiOS/releases/download/repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS repositories for kernels and optimized packages
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist
