#
# /etc/pacman-target.conf - Genesi OS
# Pacman configuration for target system installation
#

[options]
HoldPkg     = pacman glibc
Architecture = auto

# Misc options
#UseSyslog
Color
#NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[genesi]
SigLevel = Optional TrustAll
Server = https://raw.githubusercontent.com/zFreshy/GenesiOS/main/genesi-arch/repo/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS repositories for kernels and optimized packages
[cachyos]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/$arch/$repo
Server = https://cdn-77.cachyos.org/repo/$arch/$repo
Server = https://build.cachyos.org/repo/$arch/$repo
# Include = /etc/pacman.d/cachyos-mirrorlist
