# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
---
i18n:
     name: "Preparing your system for online installation of Genesi OS"

dontChroot: true
timeout: 10
script:
    - command: "/etc/calamares/scripts/detect-architecture"
    - command: "cp /etc/pacman-target.conf ${ROOT}/etc/pacman.conf"
