# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# shellprocess_initialize_pacman.conf
# generate pacman keyring, mirrorlist and copy them into target system
---

dontChroot: true

script:
 - command: "bash /etc/calamares/scripts/update-mirrorlist"
   timeout: 3600
   verbose: true
 - command: "bash /etc/calamares/scripts/create-pacman-keyring"
   verbose: true
 - "mkdir -p ${ROOT}/etc/pacman.d/"
 - "cp /etc/pacman.d/mirrorlist ${ROOT}/etc/pacman.d/"
 - "cp /etc/pacman.d/genesi-mirrorlist ${ROOT}/etc/pacman.d/ || true"
 - "cp -a /etc/pacman.d/gnupg ${ROOT}/etc/pacman.d/"
 - "cp /etc/resolv.conf ${ROOT}/etc/"

i18n:
 name: "initialize pacman ... ranking mirrors ... copy pacman mirrorlist and keyring to target ..."
