# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# disables running mkinitcpio while install process, it will be called once with initcpio module
---

dontChroot: true

script:
 - "mkdir -p /etc/pacman.d/hooks/"
 - "cp /etc/calamares/scripts/90-mkinitcpio-install.hook /etc/pacman.d/hooks/"
 - "mkdir -p ${ROOT}/usr/share/libalpm/scripts/"
 - "cp /etc/calamares/scripts/mkinitcpio-install-calamares ${ROOT}/usr/share/libalpm/scripts/"
 - "chmod +x ${ROOT}/usr/share/libalpm/scripts/mkinitcpio-install-calamares"
 - "mkdir -p ${ROOT}/etc/pacman.d/hooks/"
 - "cp /etc/calamares/scripts/90-mkinitcpio-install.hook ${ROOT}/etc/pacman.d/hooks/"

i18n:
 name: "modify 90-mkinitcpio-install.hook on host and chroot"
