# Calamares settings for Genesi OS
---
branding: genesi

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       genesi
  module:   packages
  config:   packages.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - packages
  - umount
- show:
  - finished

disable-cancel-during-exec: true
quit-at-end: false
