title   Genesi OS %ARCH% UEFI Default
sort-key A
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-6.6-x86_64
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-6.6-x86_64.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=auto module_blacklist=pcspkr nvme_load=yes
