# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# sets pacman options for package handling.
---

backend: pacman
skip_if_no_internet: true
update_db: false
update_system: false

operations:
  - install:
    - genesi-settings
    - genesi-kde-settings
    - genesi-welcome
    - genesi-ai-mode
  - remove:
    - cachyos-calamares-next
    - cachyos-hello
    - cachyos-settings
    - cachyos-kde-settings
