---
unpack:
    -   source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux-cachyos"
        sourcefs: "file"
        destination: "/boot/vmlinuz-linux-cachyos"
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux-cachyos-lts"
        sourcefs: "file"
        destination: "/boot/vmlinuz-linux-cachyos-lts"
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux-cachyos.img"
        sourcefs: "file"
        destination: "/boot/initramfs-linux-cachyos.img"
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/initramfs-linux-cachyos-lts.img"
        sourcefs: "file"
        destination: "/boot/initramfs-linux-cachyos-lts.img"
